name: "Publish Extension"
on:
  push:
    tags:
      - "v*"
jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Build files
        run: bun run build
      - name: Build archive
        run: bun run build:archive
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          name: MouseHunt Improved ${{ github.ref_name }}
          generate_release_notes: true
          files: |
            ./dist/extension/chrome.zip
            ./dist/extension/firefox.zip
            ./dist/mousehunt-improved.user.js
      - name: Upload to Chrome Web Store
        uses: Klemensas/chrome-extension-upload-action@1df3cdf4047a4789bc61a64a125994d8caf23572
        with:
          refresh-token: ${{ secrets.CHROME_WEBSTORE_REFRESH_TOKEN }}
          client-id: ${{ secrets.CHROME_WEBSTORE_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_WEBSTORE_CLIENT_SECRET }}
          file-name: ./dist/chrome.zip
          app-id: ${{ secrets.CHROME_WEBSTORE_ADDON_ID }}
          publish: true
      - name: Upload to Firefox Addons
        uses: maoserr/firefox_extension_publish@v1.0.4
        with:
          firefox_extension_id: "mh-improved@mouse.rip"
          file: "./dist/extension/firefox.zip"
          api_key: ${{ secrets.AUTH_API_ISSUER }}
          api_secret: ${{ secrets.AUTH_API_SECRET }}
          src_file: "./dist/archive.zip"
